
const passport = require('passport')
const GoogleStrategy = require('passport-google-oauth20').Strategy
const mongoose = require('mongoose')
const keys = require('../config/keys')

const User = mongoose.model('users');
//1 argument means we are fetching from mongoose - we loaded schema in on the User model
//User is model class - we can crease model isntances from it 

//it is the user pulled from the database in the callback below. it is NOT the google profile ID, it is the unique identifier generated by mongo in the callback.
//we dont always know what id will come through (google, linkedin, etc) so we use the id generated by mongo
//define a function to pass through to serialize user
passport.serializeUser((user, done) =>{
    //done is a callback - first arg is for error, second is identifying piece of information
    done(null, user.id);
})

passport.deserializeUser((id, done) => {
    //first arg is token stuff into cookie
    User.findById(id)
        .then(user => {
            done(null, user);
        })
})

passport.use(
    new GoogleStrategy(
        {
            clientID: keys.googleClientID,
            clientSecret: keys.googleClientSecret,
            callbackURL: '/auth/google/callback'
        }, 
        (accessToken, refreshToken, profile, done) => {
            // console.log('access token', accessToken);
            // console.log('refreshToken', refreshToken);
            // console.log('profile', profile);
            User.findOne({ googleId: profile.id })

                //result will be passed through to serialize user
                .then((existingUser)=>{
                    if (existingUser) {
                        //we already have a record with given ID
                        done(null, existingUser);
                        //null indicates no error, existingUser tells passport what user we just found
                    } else {
                        //we don't have a user record with this ID, so we can make new record
                        new User({ googleId: profile.id })
                            .save()
                        //id coming from google user's profile
                            .then(user => done(null,user))//promise callback includes changes while user is being saved
                            //chain on .then to make it asynchronous 
                    }
                })
        }
    )
);


//new GoogleStrategy() creates a new instance of the passport strategy
//passport.use asks passport to be aware that they can use Google Strategy to authenticate
//GoogleStrategy is known as a string called google when passport loads it up - this is what is called below in authentication route

